version: "3.9"
services:
  web:
    depends_on:
      - redis
      - mongo
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
